src/main/java/milos/mijatovic/fon/dto/StudentDto.java
package milos.mijatovic.fon.dto;


import java.io.Serializable;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;


public class StudentDto implements Serializable{

	
	
	private static final long serialVersionUID = 1L;
	private Long id;
	@Length(min = 10, max=10, message = "Minimum number of characters is 10")
	@NotNull(message = "Minimum number of characters is 10")
	private String indexNumber;
	@Length(min = 3, message = "Minimum number of characters is 3")
	@NotNull(message = "Minimum number of characters is 3")
	private String firstname;
	@Length(min = 3, message = "Minimum number of characters is 3")
	@NotNull(message = "Minimum number of characters is 3")
	private String lastname;
	private String email;
	private String adress;
	private CityDto cityDto;
	@Length(max = 15, message = "Max number of characters is 15")
	private String phone;
	@Min(1)
	private int currentYearOfStudy;
	public StudentDto(Long id, String indexNumber, String firstname, String lastname, String email, String adress,
			CityDto cityDto, String phone, int currentYearOfStudy) {
		super();
		this.id = id;
		this.indexNumber = indexNumber;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.adress = adress;
		this.cityDto = cityDto;
		this.phone = phone;
		this.currentYearOfStudy = currentYearOfStudy;
	}
	public StudentDto() {
		super();
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getIndexNumber() {
		return indexNumber;
	}
	public void setIndexNumber(String indexNumber) {
		this.indexNumber = indexNumber;
	}
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getAdress() {
		return adress;
	}
	public void setAdress(String adress) {
		this.adress = adress;
	}
	public CityDto getCityDto() {
		return cityDto;
	}
	public void setCityDto(CityDto cityDto) {
		this.cityDto = cityDto;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public int getCurrentYearOfStudy() {
		return currentYearOfStudy;
	}
	public void setCurrentYearOfStudy(int currentYearOfStudy) {
		this.currentYearOfStudy = currentYearOfStudy;
	}
	@Override
	public String toString() {
		return "StudentDto [id=" + id + ", indexNumber=" + indexNumber + ", firstname=" + firstname + ", lastname="
				+ lastname + ", email=" + email + ", adress=" + adress + ", cityDto=" + cityDto + ", phone=" + phone
				+ ", currentYearOfStudy=" + currentYearOfStudy + "]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((indexNumber == null) ? 0 : indexNumber.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StudentDto other = (StudentDto) obj;
		if (indexNumber == null) {
			if (other.indexNumber != null)
				return false;
		} else if (!indexNumber.equals(other.indexNumber))
			return false;
		return true;
	}
	public String getFullname() {
		return firstname + " " + lastname;
	}
	
	
	
}

src/main/java/milos/mijatovic/fon/controller/HomeController.java
package milos.mijatovic.fon.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

@Controller
@RequestMapping("/home")
public class HomeController {

	
	
	@GetMapping(value="/home")
	public ModelAndView home() {
		return new ModelAndView("/home/home");
	}
}

src/main/java/milos/mijatovic/fon/controller/StudentController.java
package milos.mijatovic.fon.controller;

import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.StringTrimmerEditor;
import org.springframework.stereotype.Controller;
import org.springframework.validation.Errors;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;

import milos.mijatovic.fon.dto.CityDto;
import milos.mijatovic.fon.dto.ExamRegistrationDto;
import milos.mijatovic.fon.dto.StudentDto;
import milos.mijatovic.fon.exception.DataNotFoundException;
import milos.mijatovic.fon.service.CityService;
import milos.mijatovic.fon.service.ExamRegistrationService;
import milos.mijatovic.fon.service.ProfessorService;
import milos.mijatovic.fon.service.StudentService;
import milos.mijatovic.fon.validator.StudentDtoValidator;


@Controller
@RequestMapping(value = "/student")
public class StudentController {
	
	
	private final CityService cityService;
	private final StudentService studentService;
	private final ProfessorService professorService;
	private final ExamRegistrationService examRegistrationService;
	
	@Autowired
	public StudentController(StudentService studentService, CityService cityService, ProfessorService professorService, ExamRegistrationService examRegistrationService) {
		this.studentService = studentService;
		this.cityService = cityService;
		this.professorService = professorService;
		this.examRegistrationService = examRegistrationService;
	}
	
	
	
	@GetMapping
	public ModelAndView home() {
		ModelAndView modelAndView = new ModelAndView("/student/home");
		return modelAndView;
	}
	
	@GetMapping(value = "/all")
	public ModelAndView all() {
		ModelAndView modelAndView = new ModelAndView("/student/all");
		return modelAndView;
	}
	@GetMapping(value = "/add")
	public ModelAndView add(SessionStatus sessionStatus) {
		sessionStatus.setComplete();
		ModelAndView modelAndView = new ModelAndView("/student/add");
		return modelAndView;
	}
	@PostMapping(value = "/save")
	public ModelAndView save(@Valid
			@ModelAttribute("studentDto") StudentDto studentDto, Errors erros, SessionStatus sessionStatus) {
		ModelAndView modelAndView = new ModelAndView();
		if(erros.hasErrors()) {
			modelAndView.setViewName("/student/add");
			modelAndView.addObject("studentDto", studentDto);
			System.out.println(studentDto);
		}
		else {
			studentService.save(studentDto);
			sessionStatus.setComplete();
			modelAndView.setViewName("redirect:/student/all");
		}
		
		return modelAndView;
	}
	@GetMapping(value = "/edit")
	public ModelAndView edit(@RequestParam ("id") Long id) {
		ModelAndView modelAndView = new ModelAndView("/student/edit");
		modelAndView.addObject("studentDto", studentService.findById(id));
		return modelAndView;
	}
	@PostMapping(value = "/update")
	public ModelAndView update(@Valid @ModelAttribute ("studentDto") StudentDto studentDto, Errors errors, SessionStatus sessionStatus) {
		ModelAndView modelAndView = new ModelAndView();
		if(errors.hasErrors()) {
			modelAndView.setViewName("/student/edit");
			modelAndView.addObject("studentDto", studentDto);
		}
		else {
		studentService.save(studentDto);
		sessionStatus.setComplete();
		modelAndView.setViewName("redirect:/student/all");
		}
		return modelAndView;
	}
	
	@GetMapping("/remove")
	public ModelAndView remove(@RequestParam("id") Long id) throws DataNotFoundException {
		ModelAndView modelAndView = new ModelAndView("redirect:/student/all");
		StudentDto studentDto = studentService.findById(id);
		examRegistrationService.findByStudent(studentDto);
		studentService.deleteById(id);
		return modelAndView;
	}
	@GetMapping("/details")
	public ModelAndView details(@RequestParam("id") Long id) {
		ModelAndView modelAndView = new ModelAndView("/student/details");
		StudentDto studentDto = studentService.findById(id);
		List<ExamRegistrationDto> examRegistrations = examRegistrationService.currentlyRegisteredExams(id);
		modelAndView.addObject("studentDto", studentDto);
		modelAndView.addObject("examRegistrations", examRegistrations);
		return modelAndView;
	}
	
	@ModelAttribute(value="students")
	public List<StudentDto> students(){
		return studentService.getAll();
	}
	@ModelAttribute(value="studentDto")
	public StudentDto studentDto() {
		return new StudentDto();
	}
	@ModelAttribute(value = "cities")
	public List<CityDto> cities(){
	
		return cityService.getAll();
	}
	@InitBinder
	public void initBinder(WebDataBinder binder) {
		binder.addValidators(new StudentDtoValidator(studentService, professorService));
		binder.registerCustomEditor(String.class, new StringTrimmerEditor(true));
	}
	@ExceptionHandler(DataNotFoundException.class)
	public ModelAndView dataNotFound(DataNotFoundException dataNotFoundException) {
		ModelAndView modelAndView = new ModelAndView("/student/all");
		modelAndView.addObject("errorMessage", dataNotFoundException.getMessage());
		modelAndView.addObject("students", students());
		return modelAndView;
	}
}

src/main/webapp/WEB-INF/pages/student/add.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
  pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title></title>
<style>
body {
  padding-top: 56px;
    display: flex;
    position: relative;
    flex-direction: column;
    height: 100vh;
}
.fill{
flex: 1;
}
</style>
</head>

<body data-gr-c-s-loaded="true">

<div class="container fill">
    <div class="row">
      <div class="col-md-7 offset-3">
        <br>
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">Add Student</h2>

  <form:form class ="horizontal" action="${pageContext.request.contextPath}/student/save"
    method="post" modelAttribute="studentDto">
    <fieldset>

    <div class="form-group row">
            <form:label path="indexNumber" class="col-sm-3 col-form-label">Index Number</form:label>
            <div class="col-sm-8">
            <form:input type="text" class="form-control" path="indexNumber"
                id="indexNumberId" />
            <div><form:errors path="indexNumber"  cssClass="alert-danger" /></div>
            </div>
        </div>
      <div class="form-group row">
            <form:label path="firstname" class="col-sm-3 col-form-label">First name</form:label>
            <div class="col-sm-8">
            <form:input type="text" class="form-control" path="firstname"
                id="firstnameId" />
            <div><form:errors path="firstname"  cssClass="alert-danger" /></div>
            </div>
        </div>
          <div class="form-group row">
            <form:label class="col-sm-3 col-form-label" path="lastname">Last name</form:label>
            <div class="col-sm-8">
            <form:input type="text" path="lastname" class="form-control"
                id="lastnameId" />
           <div><form:errors path="lastname" cssClass="alert-danger" /></div>
         </div>
         </div>
           <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="email">Email</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="email" id="emailId" class="form-control"/>
           <div> <form:errors path="email" cssClass="alert-danger" /></div>
         </div>
       </div>
             <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="adress">Address</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="adress" id="adressId" class="form-control"/>
           <div> <form:errors path="adress" cssClass="alert-danger" /></div>
         </div>
       </div>
          <div class="form-group row">
            <form:label path="cityDto" class="col-sm-3 col-form-label">City</form:label>
            <div class="col-sm-8">
            <form:select path="cityDto" class="form-control">
                <form:option value="" label="Choose City"></form:option>
                <form:options items="${cities}" itemValue="id" itemLabel="name" />
              </form:select>
               <div> <form:errors path="cityDto" cssClass="alert-danger" /></div>
                </div>
                </div>
            <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="phone">Phone</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="phone" id="phoneId" class="form-control"/>
           <div> <form:errors path="phone" cssClass="alert-danger" /></div>
         </div>
       </div>
        <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="currentYearOfStudy">Current Year</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="currentYearOfStudy" id="currentYearOfStudyId" class="form-control"/>
           <div> <form:errors path="currentYearOfStudy" cssClass="alert-danger" /></div>
         </div>
       </div>

            <button id="save" class="btn btn-primary">Save</button>
    </fieldset>
  </form:form>
    </div>
  </div>
</div>
</div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/pages/student/all.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<div class="container fill">
<table class="table table-striped">
<tbody>
	<tr>
		<th>Index number</th>
		<th>First name</th>
    	<th>Last name </th>
    	<th>Email</th>
    	<th>Address</th>
    	<th>City</th>
    	<th>Phone</th>
    	<th>Current year</th>
    	<th>Details</th>
    	<th>Edit</th>
    	<th>Remove</th>
	</tr>
	<c:forEach items="${students}" var="student">
		
		<c:url value="/student/remove"  var="studentRemove">
		<c:param name="id" value="${student.id}"></c:param>
		</c:url>
		<c:url value="/student/edit" var="studentEdit">
		<c:param name="id" value="${student.id}"></c:param>
		</c:url>
		<c:url value="/student/details" var="studentDetails">
		<c:param name="id" value="${student.id}"></c:param>
		</c:url>
    	<tr>
    	<td>${student.indexNumber}</td>
    	<td>${student.firstname}</td>
    	<td>${student.lastname} </td>
    	<td>${student.email} </td>
    	<td>${student.adress}</td>
    	<td>${student.cityDto.name}</td>
    	<td>${student.phone}</td>
    	<td>${student.currentYearOfStudy}</td>
    	<td><a href="${studentDetails}">Details</a> </td>
    	<td><a href="${studentEdit}">Edit</a> </td>
    	<td><a href="${studentRemove}" onclick="return confirm('Are you sure you wanna remove this subject?')">Remove</a> </td>
    	 </tr>
</c:forEach>
</tbody>
</table>
<c:if test="${not empty errorMessage }"><div class="alert alert-danger" role="alert"> ${errorMessage}</div></c:if>
				</div>
</div>

src/main/webapp/WEB-INF/pages/student/details.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    
     <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<div class="container fill">

<table class="table table-striped">

<tbody>
	<tr>
		<th>Index number</th>
		<th>First name</th>
    	<th>Last name </th>
    	<th>Email</th>
    	<th>Address</th>
    	<th>City</th>
    	<th>Phone</th>
    	<th>Current year</th>
	</tr>
	<tr>
    	<td>${studentDto.indexNumber}</td>
    	<td>${studentDto.firstname}</td>
    	<td>${studentDto.lastname} </td>
    	<td>${studentDto.email} </td>
    	<td>${studentDto.adress}</td>
    	<td>${studentDto.cityDto.name}</td>
    	<td>${studentDto.phone}</td>
    	<td>${studentDto.currentYearOfStudy}</td>
    	</tr>
    	</tbody>
    	</table>
    		<div class="text-center">All Registered Exams</div>
    	<table class="table table-striped">
<tbody>
	<tr>
		<th>Subject</th>
		<th>Professor</th>
		<th>Date</th>
	</tr>
	<c:forEach items="${examRegistrations}" var="examreg">
    	<tr>
    	<td>${examreg.examDto.subjectDto.name}</td>
    	<td>${examreg.examDto.professorDto.fullname}</td>
    	<td>${examreg.examDto.date}</td>
    	 </tr>
</c:forEach>
</tbody>
</table>
    	</div>
    	
    	

src/main/webapp/WEB-INF/pages/student/edit.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
  pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title></title>
<style>
body {
  padding-top: 56px;
    display: flex;
    position: relative;
    flex-direction: column;
    height: 100vh;
}
.fill{
flex: 1;
}
</style>
</head>

<body data-gr-c-s-loaded="true">

<div class="container fill">
    <div class="row">
      <div class="col-md-7 offset-3">
        <br>
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">Edit Student</h2>

  <form:form class ="horizontal" action="${pageContext.request.contextPath}/student/update"
    method="post" modelAttribute="studentDto">
    <fieldset>
	 <form:hidden path="id"
								id="idId" />
    <div class="form-group row">
            <form:label path="indexNumber" class="col-sm-3 col-form-label">Index Number</form:label>
            <div class="col-sm-8">
            <form:input type="text" class="form-control" path="indexNumber"
                id="indexNumberId" />
            <div><form:errors path="indexNumber"  cssClass="alert-danger" /></div>
            </div>
        </div>
      <div class="form-group row">
            <form:label path="firstname" class="col-sm-3 col-form-label">First name</form:label>
            <div class="col-sm-8">
            <form:input type="text" class="form-control" path="firstname"
                id="firstnameId" />
            <div><form:errors path="firstname"  cssClass="alert-danger" /></div>
            </div>
        </div>
          <div class="form-group row">
            <form:label class="col-sm-3 col-form-label" path="lastname">Last name</form:label>
            <div class="col-sm-8">
            <form:input type="text" path="lastname" class="form-control"
                id="lastnameId" />
           <div><form:errors path="lastname" cssClass="alert-danger" /></div>
         </div>
         </div>
           <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="email">Email</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="email" id="emailId" class="form-control"/>
           <div> <form:errors path="email" cssClass="alert-danger" /></div>
         </div>
       </div>
             <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="adress">Address</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="adress" id="adressId" class="form-control"/>
           <div> <form:errors path="adress" cssClass="alert-danger" /></div>
         </div>
       </div>
          <div class="form-group row">
            <form:label path="cityDto" class="col-sm-3 col-form-label">City</form:label>
            <div class="col-sm-8">
            <form:select path="cityDto" class="form-control">
                <form:option value="" label="Choose City"></form:option>
                <form:options items="${cities}" itemValue="id" itemLabel="name" />
              </form:select>
               <div> <form:errors path="cityDto" cssClass="alert-danger" /></div>
                </div>
                </div>
            <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="phone">Phone</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="phone" id="phoneId" class="form-control"/>
           <div> <form:errors path="phone" cssClass="alert-danger" /></div>
         </div>
       </div>
        <div class="form-group row">
           <form:label  class="col-sm-3 col-form-label" path="currentYearOfStudy">Current Year</form:label>
           <div class="col-sm-8">
            <form:input type="text" path="currentYearOfStudy" id="currentYearOfStudyId" class="form-control"/>
           <div> <form:errors path="currentYearOfStudy" cssClass="alert-danger" /></div>
         </div>
       </div>

            <button id="save" class="btn btn-primary">Save</button>
    </fieldset>
  </form:form>
    </div>
  </div>
</div>
</div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/pages/student/home.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>


<div>STUDENT HOME</div>